### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by barcodigital** [abukwaik/Radix#1]
Where Can I Find the sample data ? Or the XML file?
Import Demo Content button not this available.
The Radix -Core plugin , I can not find .

http://full.radixtheme.com/

**Comment by abukwaik** [comment]
Hi barcodigital, 

Sorry i missed this. Well, this link is referral to Radix full theme which is still under developing, As for now, the available theme is [starter Radix](https://wordpress.org/themes/radix/) and it doesn't come with sample data but you can use the [Theme Unit Test](https://codex.wordpress.org/Theme_Unit_Test) which contains dummy content for WordPress theme development.

Example: http://starter.radixtheme.com/

I'll try to upload the full radix as soon as possible,

Thank you.

**Comment by alexbritodev** [comment]
I am also awaiting the example ever built for upload.

The theme is great and very light.

NOTE: When installing the template does not appear to install the Radix-Core plugin ... although he is in the template in the admin folder. I tried to install it manually, but does not work either. When you create a post or a page does not appear in the template shortcodes options. What can it be ?? Or is correction ??

We wait friend. A big hug. Congratulations for your work.

**Comment by abukwaik** [comment]
Hi alexhpb,

Thank you for your kind words. If i understand correctly, you talking about full radix theme? Would please mention what version do you have?

**Comment by alexbritodev** [comment]
Hi... version 1.1.1 (Full Radix Theme)

**Comment by abukwaik** [comment]
Hi there alexhpb,

Well, the Full Radix version is yet unpublished. Actually, I was planing to release it very soon maybe in a few days. It will be available as an "open source" project licensed under GPL v2 or later.

Thank you!

**Comment by alexbritodev** [comment]
OK bro ...

But see if you can release this full version for us.
It is wonderful. Great job.

For those who did a version of this can make thousands.

A big hug.
