### ISSUE TITLE
Bad code in theme with redux and some extra

### ISSUE THREAD

**Issue by yupii1986** [abukwaik/Radix#2]
Hi,
I see that something is not ok because:
- if i install another plugin with redux theme options, redux options from redux will disappeared. If i will disable that plugin, is ok. I thought is issue from plugin, but i created simple theme with redux and tested with manny themes on redux and are ok.

Please fix and will be great if you can add some stuff like:
- in every page/post add posibility to add header image and breadcumber ex: http://goo.gl/fm2eyz
- hide/show title
-  woocommerce
- theme full width / boxed
- blog design like http://goo.gl/XxccWI   or http://goo.gl/5b8y0a

**Comment by abukwaik** [comment]
Hi there yupii1986,

I'm afraid you missed that Radix starter is an ultra minimal starter Theme for use as a starting template for easy WordPress Development, These features that you looking for could be available in full / premium themes.

About the plugin issue, Would you please provide the plugin name and link?

**Comment by yupii1986** [comment]
Hi,
Yes i know, but how much will cost me to add those in my theme ?
Plugin is comercial, name: LMM
Can you send email to: http://tny.im/2rr   and i will attash to you ?

**Comment by abukwaik** [comment]
Hi yupii1986,

Unfortunately, I don't offer a custom theme features. Radix is an "open source" project and is provided "AS IS".
Also please note that i do only support the plugins in the WordPress repository (Free Versions).

**Comment by yupii1986** [comment]
Yes, but i want to help you to solve your issue. As you wish. Manny thanks.
Can you advise me how to create an great full repsponsive theme, light, fast minify code , compress, and for theme options what you advise me to use: redux, theme options? You know something about theme customiser, all thme has to be with this without theme options?

Thanks again.

**Comment by abukwaik** [comment]
Hi yupii1986, Sorry for the late replay.

Well, it's a big subject actually :grinning: 

I don't know where to begin.. i guess you can start with very good "tutsplus" tutorial series founded [here](http://code.tutsplus.com/series/making-the-perfect-wordpress-theme--wp-33987)
Also, I've learned a lot from [these great lessons](https://www.youtube.com/user/LearnWebCode/playlists)

About responsiveness, it is really up to your choice, For example i like and used [Bootstrap framework](http://getbootstrap.com/) but there are many great frameworks like [Gumby](http://www.gumbyframework.com/), [Foundation](http://foundation.zurb.com/), [HTML5 Boilerplate](https://html5boilerplate.com/) and many others.

About website performance, Maybe you should follow the Google PageSpeed Insights Rules and best practices [here](https://developers.google.com/speed/docs/insights/rules?hl=en). also i found [this site](https://varvy.com/pagespeed/) is very useful.. Well, It's not an easy process but i believe it is "a must" to learn.

Same as Theme option frameworks, I'd recommend Redux framework but i also like [OptionTree](https://wordpress.org/plugins/option-tree/)

About theme customiser, i believe it is well developed and yet, the easiest way to add some options to control your theme, but yet I'd prefer to use redux framework myself :smile:

Regards.
